server:
  port: 8088
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  application:
    name: dataWay-demo
  datasource:
    url: jdbc:p6spy:postgresql://172.81.205.216:2345/gpdb
    username: gpadmin
    password: tcloud@2021
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin

decorator:
  datasource:
    p6spy:
      logging: slf4j
      log-file: dataWaySpy.log
      log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)


# dataWay
HASOR_DATAQL_DATAWAY: true
HASOR_DATAQL_DATAWAY_ADMIN: true
HASOR_DATAQL_DATAWAY_API_URL: /api/
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
HASOR_DATAQL_FX_PAGE_DIALECT: postgresql

